title: Brian Stettenbenz
email: bgstettenbenz@outlook.com
logo: /assets/github-proile-photo-min.jpeg
description: "DataRealms: Powering Insights with Real-World Data"
#show_downloads: true
theme: jekyll-theme-minimal
